- platform: broadlink
  host: 192.168.86.147
  mac: '34:ea:34:40:60:99'
  friendly_name: "Great Room Remote"
  timeout: 15
  switches:
    tv:
      friendly_name: "Great Room TV Power"
      command_on: 'JgBQAAABKJQSExITEjgSExISEhMSExITEjgTNhITEjgSOBI4EjcSOBITEhMSExI3EhMSExITEhMSNxI4EjgSExI3EzcTNxI3EwAFKQABJ0sTAA0FAAAAAAAAAAA=='
    tv_input:
      friendly_name: "TV Antenna Input"
      command_on: 'JgBQAAABKJMTEhMSEjgTEhITEhISExITEjgSNxMSEjgSOBI3EzcSOBI3EjgTNxI3EhMSExITEhMSEhMSExITEhI4EjcSOBI4EgAFKgABJ0sSAA0FAAAAAAAAAAA=='
    tv_input_select:
      friendly_name: "Input Select"
      command_on: 'JgBYAAABKJQSExITEjgTEhMSERMSExMSEzcTNhMSEjgSOBI3EzcTNxI3EzcTEhM3ExISExETEhMSExMSEzcSEhM3EzcSNxI4EwAFKQABKEoTAAxaAAEoShMADQU=='
    sound_bar_vol_up:
      friendly_name: "Volume Up"
      command_on: 'JgBYAAABJpQSFBISExISExITFBESExISEzgSNxI4EhMSNxU2EjcSOBITEhMSEhUQEhQSEhMSEhMUNhI3EzgSNxI4FDYSNxI4FQAFQAABJ0oSAAxSAAEnShIADQU=='
    sound_bar_vol_down:
      friendly_name: "Volume Down"
      command_on: 'JgBYAAABJ5QSExISExISFBISExISExITEjgSNxI4ExISOBI4EjcSOBM3EhMSExITEhITEhIUEhITEhI4EjgSNxI4EzcSOBI3EwAFQgABJ0sSAAxSAAEmSxIADQU=='
    sound_bar_vol_mute:
      friendly_name: "Volume Mute"
      command_on: 'JgBQAAABJ5MTExEUEhITEhITEhMTEhITEzcROBM3EhMTNxI4ETgTNxITExISNxMTETgTEhITExITNxI4ERQSNxITEjgSNxM4EwAFQQABJ0oSAA0FAAAAAAAAAAA=='
