- platform: cast
  name: Great Room Speaker
  host: 192.168.86.70

- platform: cast
  name: Office Speaker
  host: 192.168.86.72

- platform: cast
  name: Master Bedroom Speaker
  host: 192.168.86.74

- platform: cast
  name: Rec Room Speaker
  host: 192.168.86.76

- platform: cast
  name: Great Room TV
  host: 192.168.86.80

- platform: cast
  name: Master Bedroom TV
  host: 192.168.86.82

- platform: cast
  name: Rec Room TV
  host: 192.168.86.84

- platform: cast
  name: JBL Office Speaker
  host: 192.168.86.90

- platform: directv
  name: DirecTV Great Room
  host: 192.168.86.142

- platform: directv
  name: DirecTV Rec Room
  host: 192.168.86.143

- platform: directv
  name: DirecTV Master Bedroom
  host: 192.168.86.141

# - platform: universal
#   name: Universal Control Great Room
#   children:
#     - media_player.great_room_tv
#     - media_player.directv_great_room
#   commands:
#     turn_on:
#       service: media_player.turn_on
#       data:
#         entity_id: media_player.directv_great_room
#     turn_off:
#       service: media_player.turn_off
#       data:
#         entity_id: media_player.directv_great_room
#     # volume_up:
#     #   service: switch.turn_on
#     #   data:
#     #     entity_id: switch.living_room_volume_up
#     # volume_down:
#     #   service: switch.turn_on
#     #   data:
#     #     entity_id: switch.living_room_volume_down
#     # volume_mute:
#     #   service: switch.turn_on
#     #   data:
#     #     entity_id: switch.living_room_mute
#     # select_source:
#     #   service: media_player.select_source
#     #   data_template:
#     #     entity_id: media_player.receiver
#     #     source: '{{ source }}'
#     volume_set:
#       service: media_player.volume_set
#       data_template:
#         entity_id: media_player.receiver
#         volume_level: '{{ volume_level }}'
#   attributes:
#     state: switch.living_room_tv
#     is_volume_muted: switch.living_room_mute
#     volume_level: media_player.receiver|volume_level
#     source: media_player.receiver|source
#     source_list: media_player.receiver|source_list
