rec_room_jeopardy:
  alias: "Rec Room Jeopardy Time"
  sequence:
    - service: remote.turn_on
      entity_id: remote.rec_room_hub
      data:
        activity: "30863949"
    - service: light.turn_on
      entity_id: light.rec_room_lights
      data:
        brightness_pct: 25


- alias: 'Jeopardy Time'
  trigger:
    platform: time
    at: '18:58:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.turn_on
    entity_id: script.rec_room_jeopardy

- alias: 'Jeopardy Off'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.turn_off
    entity_id: script.rec_room_jeopardy

- alias: 'Sleep Sounds: Automatically Turn Off'
  trigger:
    - platform: state
      entity_id: media_player.master_bedroom_speaker
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.sleep_sounds_timer

- alias: 'Sleep Sounds: Reset Timer'
  trigger:
    - platform: state
      entity_id: media_player.master_bedroom_speaker
      to: 'off'
  action:
    - service: script.turn_off
      entity_id: script.sleep_sounds_timer

jeopardy_and_wheel:
  alias: "Jeopardy and Wheel of Fortune Time"
  sequence:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.great_room_tv
        media_content_id: https://www.youtube.com/watch?v=PJBmeqpw3DY
        media_content_type: video/youtube
