- platform: yr
  monitored_conditions:
  - precipitation
  - humidity
  - temperature
  - windSpeed
  - windDirection

- platform: google_wifi
  name: Google Wifi
  monitored_conditions:
    - uptime
    - status

- platform: crimereports
  name: Daily Crime
  radius: 5000

- platform: time_date
  display_options:
  - 'time'

- platform: moon
