- platform: yr
  monitored_conditions:
  - precipitation
  - humidity
  - temperature
  - windSpeed
  - windDirection

- platform: google_wifi
  name: Google Wifi
  monitored_conditions:
    - uptime
    - status
    - local_ip

- platform: crimereports
  name: Daily Crime
  radius: 5000

- platform: time_date
  display_options:
  - 'time'

- platform: moon

- platform: pi_hole
  host: 192.168.86.10/admin/api.php
  monitored_conditions:
    - ads_percentage_today
    - dns_queries_today
    - unique_clients

- platform: speedtest
  minute: 00
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

- platform: opensky
  radius: 10

- platform: template
  sensors:
    primary_router:
      friendly_name: "Primary Router"
      value_template: >-
        {% if is_state('sensor.primary_router', 'on') %}
          Transmitting
        {% else %}
          Not Transmitting
        {% endif %}
