title: KudelaCorp Headquarters
views:
    # View tab title.
  - icon: mdi:home-assistant
    title: Example
    cards:
      - type: entities
        title: Lights
        show_head_toggle: true
        entities:
          - group.all_lights
          - light.porch
      - type: media-control
        entity: media_player.master_bedroom_display
      - type: thermostat
        entity: climate.sensi_thermostat
      - type: picture-glance
        title: Front Door
        entities:
          - light.porch
        camera_image: camera.front_door
      - type: history-graph
        title: 'Motion Detection'
        entities:
          - binary_sensor.front_door_camera_person_detected
  - title: Media Players
    cards:
      - type: media-control
        entity: media_player.playroom_speaker
      - type: media-control
        entity: media_player.master_bedroom_display
      - type: media-control
        entity: media_player.master_bedroom_tv_2
      - type: media-control
        entity: media_player.master_bedroom_speaker
      - type: media-control
        entity: media_player.jbl_office_speaker
      - type: media-control
        entity: media_player.office_hub
      - type: media-control
        entity: media_player.great_room_tv
      - type: media-control
        entity: media_player.great_room_display
      - type: media-control
        entity: media_player.great_room_speaker
      - type: media-control
        entity: media_player.rec_room_speaker
      - type: media-control
        entity: media_player.rec_room_tv
