title: KudelaCorp Headquarters
views:

  - icon: mdi:security
    title: Security
    cards:
    - type: vertical-stack
      cards:
        - type: picture-glance
          title: Front Door
          entities:
            - light.porch
          camera_image: camera.front_door
        - type: history-graph
          title: 'Front Door Motion Detection'
          entities:
            - binary_sensor.front_door_camera_motion_detected
    - type: vertical-stack
      cards:
        - type: picture-glance
          title: Back Door
          entities:
            - light.sink
          camera_image: camera.kitchen
        - type: history-graph
          title: 'Back Door Motion Detection'
          entities:
            - binary_sensor.kitchen_camera_motion_detected


  - icon: mdi:lightbulb-outline
    title: Lights
    cards:
      - type: entities
        show_head_toggle: false
        entities:
          - group.all_lights
      - type: light
        entity: light.great_room_lights
        name: Great Room Lights
      - type: light
        entity: light.rec_room_lights
        name: Rec Room Lights
      - type: light
        entity: light.porch
        name: Porch Lights
      - type: light
        entity: light.garage
        name: Garage Lights
      - type: light
        entity: light.office
        name: Office Lights
      - type: light
        entity: light.sink_light
        name: Kitchen Lights


  - icon: mdi:oil-temperature
    title: Climate and Automations
    cards:
      - type: thermostat
        entity: climate.sensi_thermostat
      - type: entities
        entities:
          - automation.front_lights_on_at_sunset
          - automation.front_lights_on_at_sunset_christmas
          - automation.front_lights_off_at_sunrise
      - type: weather-forecast
        entity: weather.dark_sky


  - icon: mdi:access-point-network
    title: Network
    cards:
      - type: glance
        title: Internet Status
        entities:
          - entity: sensor.google_wifi_status
            name: Status
          - entity: sensor.google_wifi_local_ip
            name: Local IP
          - entity: sensor.google_wifi_uptime
            name: Uptime
          - entity: binary_sensor.primary_router
            name: Router


  - title: Media Players
    cards:
      - type: media-control
        entity: media_player.playroom_speaker
      - type: media-control
        entity: media_player.master_bedroom_display
      - type: media-control
        entity: media_player.master_bedroom_tv_2
      - type: media-control
        entity: media_player.master_bedroom_speaker
      - type: media-control
        entity: media_player.jbl_office_speaker
      - type: media-control
        entity: media_player.office_hub
      - type: media-control
        entity: media_player.great_room_tv
      - type: media-control
        entity: media_player.great_room_display
      - type: media-control
        entity: media_player.great_room_speaker
      - type: media-control
        entity: media_player.rec_room_speaker
      - type: media-control
        entity: media_player.rec_room_tv
