title: KudelaCorp Headquarters
views:

  - icon: mdi:home-assistant
    title: Example
    cards:

      - type: media-control
        entity: media_player.master_bedroom_display
      - type: thermostat
        entity: climate.sensi_thermostat
      - type: picture-glance
        title: Front Door
        entities:
          - light.porch
        camera_image: camera.front_door
      - type: history-graph
        title: 'Motion Detection'
        entities:
          - binary_sensor.front_door_camera_person_detected

  - icon: mdi:lightbulb-outline
    title: Lights
    cards:
      - type: entities
        show_head_toggle: false
        entities:
          - group.all_lights
      - type: light
        entity: light.great_room_lights
        name: Great Room Lights
      - type: light
        entity: light.rec_room_lights
        name: Rec Room Lights
      - type: light
        entity: light.porch
        name: Porch Lights
      - type: light
        entity: light.garage
        name: Garage Lights
      - type: light
        entity: light.tall_office_lamp
        name: Tall Office Lamp

  - icon: mdi:access-point-network
    title: Network
    cards:
      - type: sensor
        entity: sensor.google_wifi_status
        name: Google Wifi Status

  - title: Media Players
    cards:
      - type: media-control
        entity: media_player.playroom_speaker
      - type: media-control
        entity: media_player.master_bedroom_display
      - type: media-control
        entity: media_player.master_bedroom_tv_2
      - type: media-control
        entity: media_player.master_bedroom_speaker
      - type: media-control
        entity: media_player.jbl_office_speaker
      - type: media-control
        entity: media_player.office_hub
      - type: media-control
        entity: media_player.great_room_tv
      - type: media-control
        entity: media_player.great_room_display
      - type: media-control
        entity: media_player.great_room_speaker
      - type: media-control
        entity: media_player.rec_room_speaker
      - type: media-control
        entity: media_player.rec_room_tv
