- platform: yr
  monitored_conditions:
    - precipitation
    - humidity
    - temperature
    - windSpeed
    - windDirection

- platform: google_wifi
  name: Google Wifi
  monitored_conditions:
    - uptime
    - status
    - local_ip

- platform: crimereports
  name: Daily Crime
  radius: 10000

- platform: time_date
  display_options:
  - 'time'

- platform: moon

- platform: pi_hole
  host: 192.168.86.10/admin/api.php
  monitored_conditions:
    - ads_percentage_today
    - dns_queries_today
    - unique_clients

- platform: speedtest
  minute: 00
  hour:
    - 0
    - 6
    - 12
    - 18
  monitored_conditions:
    - ping
    - download
    - upload

- platform: opensky
  radius: 10

- platform: darksky
  api_key: 758ee8f868d02bad17fcb360192cbcdd
  forecast:
    - 0
    - 1
    - 2
    - 3
  monitored_conditions:
    - summary
    - icon
    - temperature
    - nearest_storm_distance
  update_interval:
    days: 0
    hours: 0
    minutes: 5

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use_percent
    - type: ipv4_address
      arg: eth0

# - platform: dte_energy_bridge
#   ip: 192.168.86.151
#   version: 2

- platform: template
  sensors:
    primary_router:
      friendly_name: "Primary Router"
      value_template: >-
        {% if is_state('binary_sensor.primary_router', 'on') %}
          Transmitting
        {% else %}
          Not Transmitting
        {% endif %}
    office_hub:
      friendly_name: "Office Hub"
      value_template: >-
        {% if is_state('binary_sensor.office_hub', 'on') %}
          Transmitting
        {% else %}
          Not Transmitting
        {% endif %}
    great_room_hub:
      friendly_name: "Great Room Hub"
      value_template: >-
        {% if is_state('binary_sensor.great_room_hub', 'on') %}
          Transmitting
        {% else %}
          Not Transmitting
        {% endif %}
